### ISSUE TITLE
Todo List

### ISSUE THREAD

**Issue by amit-ib** [amit-ib/Todo#1]
**Phase - 1**
- [ ] TD0001-Folder structuring
- [ ] TD0002-Add static Todo list
- [ ] TD0003-Functionality to add new task
- [ ] TD0004-Functionality to mark task as done
- [ ] TD0005-Functionality to edit task
- [ ] TD0006-Functionality to delete task

**Phase - 1 : Good to have**
- [ ] TD0007-Show confirmation dialog on deleting any task
- [ ] TD0008-Implement filter list functionality  
- [ ] TD0009-Sort items to display latest on top  

**Phase - 2**
- [ ] TD00010-Add date with task
- [ ] TD00011-Change date for already added task
- [ ] TD00011-Animate on deleting any task

**Phase - 3**
- [ ] TD00012-Use Redux/Stores
- [ ] TD00013-Introduce database and store todos in it

**Updations**
- [ ] TDM0001-Updation as per code review

**URL**
https://todo-3dec9.web.app/

**Comment by akash-dhande-ib** [comment]
- **PROCCESS**
 - Tickets
 - Smart Commits
 - Planning
 - CD/CI Process
 - Designing
 - **JavaScript**
 - Logic Creation
 - GitHub
 - Separation of Concern
